[theme]

# Primary Accent color for interactive elemets.
primaryColor = "#007BFF"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#28A745"

# Color used for almost all text.
textColor = "#343A40"

# Font Style
font = "sans serif"

[client]
toolbarMode = "minimal"